import image1 from "../assets/Images/VTS Python fullstack img.png";
import image3 from  "../assets/Images/VTS Java Fullstack Img.png";
import image4 from  "../assets/Images/VTS UI UX Image.png";     
import image5 from  "../assets/Images/Mern fullstack.jpg";    
import image6 from  "../assets/Images/Data Analytics image.png";    
import image7 from  "../assets/Images/Data Science Image.png";    
import image8 from  "../assets/Images/Business Analytics image.png";    
import image9 from  "../assets/Images/Mobile App development image.png";    
import image10 from  "../assets/Images/Software testing image.png";    
import image11 from  "../assets/Images/AWS images.png";    
import image12 from  "../assets/Images/Digital Marketing image.png";     



const courseData = {
    "python-fullstack": {
        title: "Python Full-Stack ",
        description: "A Python Full-Stack Development Course Covers Both Front-End And Back-End Technologies Essential For Building Dynamic Web Applications. It Includes HTML For Structuring Web Pages, CSS For Styling, And JavaScript For Interactivity. On The Back End, Python. Is Used For Server-Side Logic, While MySQL Manages Database Operations. The Course Also Covers Software Development Life Cycle (SDLC) To Understand Project Workflows And GitHub For Version Control And Collaboration. By The End Of The Course, Learners Will Gain Hands-On Experience In Developing, Managing, And Deploying Full-Stack Applications.",
        image: image1,
        duration: "45 Days",
        trainingMode: "Online/Offline",
        skillLevel: "Expert",
        certification: "Yes",
        liveClasses: "Yes",
        liveProjectTraining: "Yes",
        internshipOffer: "Yes",
        jobOffer: "Yes",
        workFromHome: "Yes",
        placementAssistance: "100%",
        trainingMaterial: "Yes",
    },
    "python-internship": {
        title: "Python Full-Stack ",
        description: "A Python Full-Stack Development Course Covers Both Front-End And Back-End Technologies To Build Dynamic Wel Applications. It Starts With HTML For Structuring Web Pages, CSS For Styling And Responsiveness, And JavaScript For Interactivity, React.Js Is Used To Create Efficient And Reusable Ul Components. On The Back End, The Course Covers RESTful APls For Communication Between The Front End And Back End, Python. For Server-Side Logic, And MySQL For Managing Databases. By The End Of The Course, Learners Will Have The Skills To Develop Complete Web Applications From Scratch..",
        image: image1,
        duration: "60 Days",
        trainingMode: "Online/Offline",
        skillLevel: "Expert",
        certification: "Yes",
        liveClasses: "Yes",
        liveProjectTraining: "Yes",
        internshipOffer: "Yes",
        jobOffer: "Yes",
        workFromHome: "Yes",
        placementAssistance: "100%",
        trainingMaterial: "Yes",
    },
    "python-internship-wfm": {
        title: "Python Full-Stack ",
        description: "A Python Fullstack course covers the essentials of software development, It starts with the Software Development Life Cycle (SDLC) for understanding project workflows, followed by HTML, CSS, and JavaScript for building responsive and interactive user interfaces. Advanced front-end skills are developed with React.js, while RESTful APls enable seamless communication between client and server. Agile methodologies are taught for effective team collaboration.On the back-end, Python is used for logic and automation, while MySQL handles database management. Finally, Data Structures prepare you for efficient data manipulation and problem-solving, offering a complete skill set for web development.",
        image: image1,
        duration: "90 Days",
        trainingMode: "Online/Offline",
        skillLevel: "Expert",
        certification: "Yes",
        liveClasses: "Yes",
        liveProjectTraining: "Yes",
        internshipOffer: "Yes",
        jobOffer: "Yes",
        workFromHome: "Yes",
        placementAssistance: "100%",
        trainingMaterial: "Yes",
    },
        "java-fullstack": {
        title: "Java Full-Stack Development",
        description: "A Java Full-Stack Development course equips learners with both front-end and back-end skills to build robust web applications. It covers HTML for structuring web pages, CSS for styling, and JavaScript for interactivity. React.js is used for creating dynamic and responsive user interfaces.On the back end, the course includes Core Java for foundational programming, Advanced Java (JSP, Servlets) for web application development, and MySQL for database management. By the end of the course, learners will have hands-on experience in building and deploying full-stack applications using Java technologies.",
        image:image3 ,
        duration: "45 Days",
        trainingMode: "Online",
        skillLevel: "Expert",
        certification: "Yes",
        liveClasses: "Yes",
        liveProjectTraining: "Yes",
        internshipOffer: "Yes",
        jobOffer: "Yes",
        workFromHome: "yes",
        placementAssistance: "100%",
        trainingMaterial: "Yes",
    },
        "java-fullstack-intern": {
        title: "Java Full-Stack Development",
        description: "A Java Full-Stack Development course equips learners with both front-end and back-end skills to build robust web applications. It covers HTML for structuring web pages, CSS for styling, and JavaScript for interactivity. React.js is used for creating dynamic and responsive user interfaces.On the back end, the course includes Core Java for foundational programming, Advanced Java (JSP, Servlets) for web application development, and MySQL for database management. By the end of the course, learners will have hands-on experience in building and deploying full-stack applications using Java technologies.",
        image:image3 ,
        duration: "60 Days",
        trainingMode: "Online",
        skillLevel: "Expert",
        certification: "Yes",
        liveClasses: "Yes",
        liveProjectTraining: "Yes",
        internshipOffer: "Yes",
        jobOffer: "Yes",
        workFromHome: "No",
        placementAssistance: "100%",
        trainingMaterial: "Yes",
    },
        "java-fullstack-wfh": {
        title: "Java Full-Stack Development",
        description: "Java Fullstack development involves creating comprehensive web applications that handle both the client side and server-side.On the front end, technologies like HTML, CSS, Bootstrap, and JavaScript are used to build responsive and interactive user interfaces.The back end is powered by Java, JEE, and frameworks like Hibernate for ORM (Object Relational Mapping), ensuring efficient database interactions with MySQL. RESTful APls facilitate communication between the front and back ends. Adhering to SDLC phases ensures systematic development, while Agile methodologies promote flexibility and collaboration. Proficiency in Data Structures enhances performance and problem-solving, making it crucial for a Java Fullstack developer.",
        image:image3 ,
        duration: "60 Days",
        trainingMode: "Online",
        skillLevel: "Advanced",
        certification: "Yes",
        liveClasses: "Yes",
        liveProjectTraining: "Yes",
        internshipOffer: "Yes",
        jobOffer: "Yes",
        workFromHome: "No",
        placementAssistance: "100%",
        trainingMaterial: "Yes",
    },
    "ui-ux-design": {
        title: "UI/UX Design Masterclass",
        description: "A UI/UX Design course equips learners with the skills to create visually appealing and user-friendly digital experiences. Using Figma, students will design wireframes, prototypes, and interactive interfaces.Photoshop helps in crafting high-quality graphics and Ul elements, while Canva simplifies the creation of visually engaging designs for social media and marketing.This course covers essential design principles, user research, and prototyping, enabling learners to build intuitive and aesthetically pleasing digital products.",
        image: image4,
        duration: "30 Days",
        trainingMode: "Online",
        skillLevel: "Expert",
        certification: "Yes",
        liveClasses: "Yes",
        liveProjectTraining: "Yes",
        internshipOffer: "No",
        jobOffer: "No",
        workFromHome: "Yes",
        placementAssistance: "100%",
        trainingMaterial: "Yes",
    },
    "ui-ux-design-intern": {
        title: "UI/UX Design Masterclass",
        description: "A UI/UX Design course equips learners with the skills to create intuitive and visually appealing digital experiences. Using Figma, students will design wireframes, prototypes, and interactive user interfaces. Adobe Photoshop helps in editing and enhancing graphics, while Adobe Illustrator is used for creating vector designs, icons, and illustrations.The course focuses on user-centric design principles, typography, color theory, and responsive layouts, ensuring a strong foundation in both Ul (User Interface) and UX (User Experience) design. By the end, learnerwill be proticient in designing professional, high-quality digital products.",
        image: image4,
        duration: "30 Days",
        trainingMode: "Online",
        skillLevel: "Beginner",
        certification: "Yes",
        liveClasses: "Yes",
        liveProjectTraining: "Yes",
        internshipOffer: "yes",
        jobOffer: "No",
        workFromHome: "Yes",
        placementAssistance: "100%",
        trainingMaterial: "Yes",
    },
    "ui-ux-design-wfh": {
        title: "UI/UX Design Masterclass",
        description: "A UI/UX course focusing on tools like Figma, Balsamia, Adobe XD, Photoshop, and Illustrator teaches you to design intuitive, user-friendly digital interfaces. You'll learn wireframing (Balsamiq), prototyping (Figma, Adobe XD), and creating visually appealing designs (Photoshop, Illustrator). These tools enable crafting interactive designs, optimizing user experiences, and visual storytelling. The course covers best practices in user research, usability testing, and designing for various platforms, preparing you for roles like UI/UX Designer.",
        image: image4,
        duration: "30 Days",
        trainingMode: "Online",
        skillLevel: "Beginner",
        certification: "Yes",
        liveClasses: "Yes",
        liveProjectTraining: "Yes",
        internshipOffer: "No",
        jobOffer: "No",
        workFromHome: "Yes",
        placementAssistance: "80%",
        trainingMaterial: "Yes",
    },
    "mern-stack": {
        title: "MERN Stack Development",
        description: "The MERN stack is o popular JavaScript-based framework used for building full-stack web applications. It includes MongoDB (a NoSQL database), Express.js (a back-end web framework), React.js and Nodejs The Software Development Life Cycle (SDLC) for a MERN stack application typically involves stages such as planning, design, development, testing, deployment, and maintenance. HTML, CSS, and JavaScript are foundational technologies used to structure, style, and add interactivity to the front end, while Node is and Express handle server-side operations and database interactions, all seamlessly integrated using JavaSeript across the stack.",
        image: image5,
        duration: "60 Days",
        trainingMode: "Online",
        skillLevel: "Intermediate",
        certification: "Yes",
        liveClasses: "Yes",
        liveProjectTraining: "Yes",
        internshipOffer: "Yes",
        jobOffer: "Yes",
        workFromHome: "Yes",
        placementAssistance: "90%",
        trainingMaterial: "Yes",
    },
    "mern-stack-internship": {
        title: "MERN Stack Development",
        description: "Covers MongoDB, Express.js, React, and Node.js for full-stack web applications.",
        image: image5,
        duration: "60 Days",
        trainingMode: "Online",
        skillLevel: "Intermediate",
        certification: "Yes",
        liveClasses: "Yes",
        liveProjectTraining: "Yes",
        internshipOffer: "Yes",
        jobOffer: "Yes",
        workFromHome: "Yes",
        placementAssistance: "90%",
        trainingMaterial: "Yes",
    },
    "data-analytics": {
        title: "Data Analytics & Training",
        description: "Learn data analysis techniques using Python, SQL, Power BI, and Excel.",
        image: image6,
        duration: "45 Days",
        trainingMode: "Online",
        skillLevel: "Intermediate",
        certification: "Yes",
        liveClasses: "Yes",
        liveProjectTraining: "Yes",
        internshipOffer: "Yes",
        jobOffer: "No",
        workFromHome: "Yes",
        placementAssistance: "85%",
        trainingMaterial: "Yes",
    },
    "data-analytics-internship": {
        title: "Data Analytics & Training",
        description: "Learn data analysis techniques using Python, SQL, Power BI, and Excel.",
        image: image6,
        duration: "45 Days",
        trainingMode: "Online",
        skillLevel: "Intermediate",
        certification: "Yes",
        liveClasses: "Yes",
        liveProjectTraining: "Yes",
        internshipOffer: "Yes",
        jobOffer: "No",
        workFromHome: "Yes",
        placementAssistance: "85%",
        trainingMaterial: "Yes",
    },
    "data-science": {
        title: "Data Science & Training",
        description: "Deep dive into Machine Learning, AI, and Big Data technologies with Python and R.",
        image: image7,
        duration: "90 Days",
        trainingMode: "Online",
        skillLevel: "Advanced",
        certification: "Yes",
        liveClasses: "Yes",
        liveProjectTraining: "Yes",
        internshipOffer: "Yes",
        jobOffer: "Yes",
        workFromHome: "Yes",
        placementAssistance: "95%",
        trainingMaterial: "Yes",
    },
    "data-science-job": {
        title: "Data Science & Training",
        description: "Deep dive into Machine Learning, AI, and Big Data technologies with Python and R.",
        image: image7,
        duration: "90 Days",
        trainingMode: "Online",
        skillLevel: "Advanced",
        certification: "Yes",
        liveClasses: "Yes",
        liveProjectTraining: "Yes",
        internshipOffer: "Yes",
        jobOffer: "Yes",
        workFromHome: "Yes",
        placementAssistance: "95%",
        trainingMaterial: "Yes",
    },
    "business-analytics": {
    title: "Business Analytics & Training",
    description: "Gain expertise in Business Analytics with hands-on training in data visualization, SQL, Excel, and predictive modeling for business decision-making.",
    image: image8,
    duration: "45 Days",
    trainingMode: "Online/Offline",
    skillLevel: "Intermediate",
    certification: "Yes",
    liveClasses: "Yes",
    liveProjectTraining: "Yes",
    internshipOffer: "Yes",
    jobOffer: "Yes",
    workFromHome: "Yes",
    placementAssistance: "100%",
    trainingMaterial: "Yes",
},
    "business-analytics-job": {
    title: "Business Analytics & Training",
    description: "Gain expertise in Business Analytics with hands-on training in data visualization, SQL, Excel, and predictive modeling for business decision-making.",
    image: image8,
    duration: "45 Days",
    trainingMode: "Online/Offline",
    skillLevel: "Intermediate",
    certification: "Yes",
    liveClasses: "Yes",
    liveProjectTraining: "Yes",
    internshipOffer: "Yes",
    jobOffer: "Yes",
    workFromHome: "Yes",
    placementAssistance: "100%",
    trainingMaterial: "Yes",
},
    "mobile-app-development": {
        title: "Mobile App Development & Training",
        description: "Build mobile apps using Flutter, React Native, and Swift.",
        image: image9,
        duration: "120 Days",
        trainingMode: "Online",
        skillLevel: "Expert",
        certification: "Yes",
        liveClasses: "Yes",
        liveProjectTraining: "Yes",
        internshipOffer: "Yes",
        jobOffer: "Yes",
        workFromHome: "Yes",
        placementAssistance: "100%",
        trainingMaterial: "Yes",
    },
    "mobile-app-development-job": {
        title: "Mobile App Development & Training",
        description: "Build mobile apps using Flutter, React Native, and Swift.",
        image: image9,
        duration: "120 Days",
        trainingMode: "Online",
        skillLevel: "Expert",
        certification: "Yes",
        liveClasses: "Yes",
        liveProjectTraining: "Yes",
        internshipOffer: "Yes",
        jobOffer: "Yes",
        workFromHome: "Yes",
        placementAssistance: "100%",
        trainingMaterial: "Yes",
    },
    "software-testing": {
        title: "Software Testing & Training",
        description: "Learn manual and automation testing using Selenium, JMeter, and TestNG.",
        image: image10,
        duration: "90 Days",
        trainingMode: "Online",
        skillLevel: "Intermediate",
        certification: "Yes",
        liveClasses: "Yes",
        liveProjectTraining: "Yes",
        internshipOffer: "Yes",
        jobOffer: "Yes",
        workFromHome: "No",
        placementAssistance: "100%",
        trainingMaterial: "Yes",
    },
    "software-testing-job": {
        title: "Software Testing & Training",
        description: "Learn manual and automation testing using Selenium, JMeter, and TestNG.",
        image: image10,
        duration: "90 Days",
        trainingMode: "Online",
        skillLevel: "Intermediate",
        certification: "Yes",
        liveClasses: "Yes",
        liveProjectTraining: "Yes",
        internshipOffer: "Yes",
        jobOffer: "Yes",
        workFromHome: "No",
        placementAssistance: "100%",
        trainingMaterial: "Yes",
    },
    "aws-training": {
        title: "Amazon Web Services (AWS) & Training",
        description: "Master cloud computing with AWS, EC2, Lambda, S3, and security best practices.",
        image: image11,
        duration: "90 Days",
        trainingMode: "Online",
        skillLevel: "Advanced",
        certification: "Yes",
        liveClasses: "Yes",
        liveProjectTraining: "Yes",
        internshipOffer: "Yes",
        jobOffer: "No",
        workFromHome: "No",
        placementAssistance: "85%",
        trainingMaterial: "Yes",
    },
    "digital-marketing": {
        title: "Digital Marketing & Training",
        description: "SEO, Google Ads, Social Media Marketing, and Content Strategy for online business growth.",
        image: image12,
        duration: "90 Days",
        trainingMode: "Online",
        skillLevel: "Intermediate",
        certification: "Yes",
        liveClasses: "Yes",
        liveProjectTraining: "Yes",
        internshipOffer: "Yes",
        jobOffer: "Yes",
        workFromHome: "Yes",
        placementAssistance: "90%",
        trainingMaterial: "Yes",
    },
    "digital-marketing-job": {
        title: "Digital Marketing & Training",
        description: "SEO, Google Ads, Social Media Marketing, and Content Strategy for online business growth.",
        image: image12,
        duration: "90 Days",
        trainingMode: "Online",
        skillLevel: "Intermediate",
        certification: "Yes",
        liveClasses: "Yes",
        liveProjectTraining: "Yes",
        internshipOffer: "Yes",
        jobOffer: "Yes",
        workFromHome: "Yes",
        placementAssistance: "90%",
        trainingMaterial: "Yes",
    }
};

export default courseData;
